name: Build Executables

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # ensure we get results for all matrix jobs
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: AMGui-linux64
          - os: windows-latest
            artifact_name: AMGui-windows64.exe
          - os: macos-latest
            artifact_name: AMGui-mac64
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      # Install wxwidgets (OS-specific)
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgtk-3-dev
        name: install wxwidgets
      - if: matrix.os == 'windows-latest'
        name: install wxwidgets
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install wxwidgets
      - if: matrix.os == 'macos-latest'
        name: install wxwidgets
        run: brew install wxmac

      - name: report perl information
        run: perl -V

      - name: install perl module dependencies
        run: cpanm -v --notest --installdeps --with-develop .

      # TODO
      # - name: unit tests
      #   run: cpanm -v --test-only .

      - name: build executable
        run: pp TrAML.pl -gui -c -o dist/${{ matrix.artifact_name }}

      - uses: actions/upload-artifact@v2
        name: upload executable
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}
          if-no-files-found: error
